User can view product details - front end
andrewkyungwonpark/wicked-sales-js pull request #4
Opened 2020-09-29 23:53 UTC by andrewkyungwonpark

![can-vew-details-frontend-AndrewPark](https://user-images.githubusercontent.com/67514987/94628218-4f9bbb00-0274-11eb-9ee4-3172c3167ec8.gif)

2020-09-29 23:56 UTC, thebearingedge requested changes
The code is fine but please finish fixing the layout of the details view.

2020-09-30 00:45 UTC, andrewkyungwonpark commented
![Uploading can-vew-details-frontend-AndrewPark updated.gif…]()

2020-09-30 00:45 UTC, andrewkyungwonpark commented
![can-vew-details-frontend-AndrewPark updated](https://user-images.githubusercontent.com/67514987/94630785-917c2f80-027b-11eb-9845-b2c890c61b4b.gif)

2020-09-30 00:47 UTC, thebearingedge approved these changes

2020-09-30 00:47 UTC, merged